engine.name=guayaquil
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-guayaquil:3306/blockbuster_guayaquil
db.user=root
db.password=root
group.id=sucursal
external.id=002
registration.url=http://symmetricds:31415/sync/quito
sync.url=http://symmetricds:31415/sync/guayaquil
auto.registration=true
initial.load.create.first=true
