engine.name=manta
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://mysql-manta:3306/blockbuster_manta
db.user=root
db.password=root
group.id=sucursal
external.id=003
registration.url=http://symmetricds:31415/sync/quito
sync.url=http://symmetricds:31415/sync/manta
auto.registration=true
initial.load.create.first=true
