engine.name=quito
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://postgres-quito:5432/blockbuster_db
db.user=blockbuster
db.password=blockbuster
group.id=central
external.id=001
registration.url=
sync.url=http://symmetricds:31415/sync/quito
auto.registration=true
initial.load.create.first=true
